### ISSUE TITLE
文档需要更新!

### ISSUE THREAD

**Issue by showgp** [efoxTeam/flutter-ui#31]
在 README 中 "环境与构建" 一节, 需要提前说明要先配置好 firebase 才能开始编译.

**Comment by ckken** [comment]
你好 目前firebase 的问题 你是什么修复的 因为依赖安装默认是会帮忙安装

**Comment by showgp** [comment]
直接把 pubspec.yaml 里面的 firebase 依赖注释掉, 另外搜索使用的位置的 firebase 注释掉即可, 工程中和 firebase 相关的代码就只有几处.

如果不注释的话需要把 firebase 的 android 端和 iOS 端配置好, 在 Firebase 的文档里面有, [专门针对 Flutter 的文档链接在这里](https://firebase.google.com/docs/flutter/setup).

只是想编译看看效果, 在 iOS 设备上搞的, 所以采用的注释这条路...

**Comment by ckken** [comment]
fix it https://github.com/efoxTeam/flutter-ui/pull/40
