### ISSUE TITLE
点击TextField页面中的任意一个textField例子报错

### ISSUE THREAD

**Issue by DevaloperHH** [efoxTeam/flutter-ui#33]
手机型号：小米8
系统版本：MIUI10.2稳定版

![Screenshot_2019-03-18-09-04-59-292_com flutter be](https://user-images.githubusercontent.com/38316554/54500951-1420f080-495d-11e9-9b72-44a800632c99.png)
![Screenshot_2019-03-18-09-05-31-638_com flutter be](https://user-images.githubusercontent.com/38316554/54500952-15521d80-495d-11e9-90f9-12c25934aa9b.png)

**Comment by DIVINER-onlys** [comment]
get，今天看下

**Comment by DevaloperHH** [comment]
> get，今天看下

O了

**Comment by DIVINER-onlys** [comment]
问题是我们在主题中设置了platform: TargetPlatform.iOS，导致Android设备上的MaterialApp中使用themeData平台是TargetPlatform.iOS，然后就出现了pasteButtonLabel警告的问题，去掉这个platform设置

**Comment by ckken** [comment]
fixed it https://github.com/efoxTeam/flutter-ui/pull/44
