### ISSUE TITLE
好多闪退...我畏惧了

### ISSUE THREAD

**Issue by ikimiler** [efoxTeam/flutter-ui#43]

**Comment by wanwusangzhi** [comment]
你好，能方便提供下机型嘛？操作场景也能否简要描述

**Comment by ikimiler** [comment]
华为mate9，点击widget进入详情页面的时候，大概率的出现闪退，也出现loadding 和 toolbar卡在屏幕正中间的情况

**Comment by ckken** [comment]
https://github.com/efoxTeam/flutter-ui/commit/9ead94be3ae0e5c700620832cb9a6d839d1b1e1b 增加crash 监控 可以试试 目前机型问题 不能一一debug 谢谢对我们支持与关注 我们会逐步优化 务求做到最好

**Comment by ckken** [comment]
https://console.cloud.google.com/storage/browser/test-lab-4t660p7zx51ca-jnsmkr3fymh3k/web-build_2019-03-19T03:53:42.204Z_ns1y/sailfish-26-en_US-portrait?authuser=0&pli=1 crash 报告

**Comment by xiashuang5112** [comment]
努比亚 z17 闪退 严重!!!

**Comment by ckken** [comment]
请试试 v1.0.1

**Comment by ckken** [comment]
请用1.0.1重试  目前没收到反馈crash


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by ckken** [comment]
请用1.0.1重试  目前没收到反馈crash


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)
