### ISSUE TITLE
闪退问题比较严重

### ISSUE THREAD

**Issue by spvycf** [efoxTeam/flutter-ui#45]

**Comment by ckken** [comment]
请问下机型版本 新版本已经优化了部分性能 1.0.1


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by ckken** [comment]
请用1.0.1重试  目前没收到反馈crash


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)
