### ISSUE TITLE
app内升级用不了，你确定您的代码没有问题吗？

### ISSUE THREAD

**Issue by xiebao** [efoxTeam/flutter-ui#50]
FlutterDownloader下载   一路正常，但是打不开下载文件？你的代码没有问题吗：

 if (taskId == id && status == DownloadTaskStatus.complete) {
        OpenFile.open(_finalApkPath);
        FlutterDownloader.open(taskId: id);
      }

提示
D/DownloadWorker( 1808): There's no application that can open the file /storage/emulated/0/app-release-flutter.apk
D/DownloadWorker( 1808): File downloaded
E/MethodChannel#open_file( 1808): Failed to handle method call
……
I/WM-WorkerWrapper( 1808): Worker result SUCCESS for Work [ id=e7a79ef0-9291-4d7d-8fec-c823921b1dd3, tags={ flutter_download_task, vn.hunghd.flutterdownloader.DownloadWorker } ]
E/flutter ( 1808): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: PlatformException(error, length=19; index=20, null)
E/flutter ( 1808): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:564:7)
……

**Comment by ckken** [comment]
解决了？
